{-# LANGUAGE OverloadedStrings, ScopedTypeVariables #-}
module Text.HeX.Math.LaTeX (defaults) where

import Text.HeX
import Text.HeX.Standard.TeX
import Control.Applicative ((<$>))
import Text.HeX.Math (defaultsFor, withText)

defaults :: HeX ()
defaults = do
  defaultsFor writer
  register "textrm" $ (ctl "textrm" +++) <$> withText
  register "text" $ (ctl "text" +++) <$> withText
  register "textit" $ (ctl "textit" +++) <$> withText
  register "texttt" $ (ctl "texttt" +++) <$> withText
  mapM_ latexCommand1 [ "mathrm"
                      , "mbox"
                      , "mathit"
                      , "mathtt"
                      , "mathsf"
                      , "mathbb"
                      , "mathcal"
                      , "mathfrak" ]
  register "sqrt" root
  register "surd" root
  mapM_ latexCommand1 [ "acute"
                      , "grave"
                      , "breve"
                      , "check"
                      , "dot"
                      , "ddot"
                      , "mathring"
                      , "vec"
                      , "overrightarrow"
                      , "overleftarrow"
                      , "hat"
                      , "widehat"
                      , "tilde"
                      , "widetilde"
                      , "bar"
                      , "overbrace"
                      , "overbracket"
                      , "overline"
                      , "underbrace"
                      , "underbracket"
                      , "underline" ]
  mapM_ latexCommand0 [ "mid"
                      , "parallel"
                      , "backslash"
                      , "setminus"
                      , "times"
                      , "alpha"
                      , "beta"
                      , "chi"
                      , "delta"
                      , "Delta"
                      , "epsilon"
                      , "varepsilon"
                      , "eta"
                      , "gamma"
                      , "Gamma"
                      , "iota"
                      , "kappa"
                      , "lambda"
                      , "Lambda"
                      , "mu"
                      , "nu"
                      , "omega"
                      , "Omega"
                      , "phi"
                      , "varphi"
                      , "Phi"
                      , "pi"
                      , "Pi"
                      , "psi"
                      , "Psi"
                      , "rho"
                      , "sigma"
                      , "Sigma"
                      , "tau"
                      , "theta"
                      , "vartheta"
                      , "Theta"
                      , "upsilon"
                      , "xi"
                      , "Xi"
                      , "zeta"
                      , "frac12"
                      , "frac14"
                      , "frac34"
                      , "frac13"
                      , "frac23"
                      , "frac15"
                      , "frac25"
                      , "frac35"
                      , "frac45"
                      , "frac16"
                      , "frac56"
                      , "frac18"
                      , "frac38"
                      , "frac58"
                      , "frac78"
                      , "pm"
                      , "mp"
                      , "triangleleft"
                      , "triangleright"
                      , "cdot"
                      , "star"
                      , "ast"
                      , "times"
                      , "div"
                      , "circ"
                      , "bullet"
                      , "oplus"
                      , "ominus"
                      , "otimes"
                      , "bigcirc"
                      , "oslash"
                      , "odot"
                      , "land"
                      , "wedge"
                      , "lor"
                      , "vee"
                      , "cap"
                      , "cup"
                      , "sqcap"
                      , "sqcup"
                      , "uplus"
                      , "amalg"
                      , "bigtriangleup"
                      , "bigtriangledown"
                      , "dag"
                      , "dagger"
                      , "ddag"
                      , "ddagger"
                      , "lhd"
                      , "rhd"
                      , "unlhd"
                      , "unrhd"
                      , "lt"
                      , "gt"
                      , "ne"
                      , "neq"
                      , "le"
                      , "leq"
                      , "leqslant"
                      , "ge"
                      , "geq"
                      , "geqslant"
                      , "equiv"
                      , "ll"
                      , "gg"
                      , "doteq"
                      , "prec"
                      , "succ"
                      , "preceq"
                      , "succeq"
                      , "subset"
                      , "supset"
                      , "subseteq"
                      , "supseteq"
                      , "sqsubset"
                      , "sqsupset"
                      , "sqsubseteq"
                      , "sqsupseteq"
                      , "sim"
                      , "simeq"
                      , "approx"
                      , "cong"
                      , "Join"
                      , "bowtie"
                      , "in"
                      , "ni"
                      , "owns"
                      , "propto"
                      , "vdash"
                      , "dashv"
                      , "models"
                      , "perp"
                      , "smile"
                      , "frown"
                      , "asymp"
                      , "notin"
                      , "gets"
                      , "leftarrow"
                      , "to"
                      , "rightarrow"
                      , "leftrightarrow"
                      , "uparrow"
                      , "downarrow"
                      , "updownarrow"
                      , "Leftarrow"
                      , "Rightarrow"
                      , "Leftrightarrow"
                      , "iff"
                      , "Uparrow"
                      , "Downarrow"
                      , "Updownarrow"
                      , "mapsto"
                      , "longleftarrow"
                      , "longrightarrow"
                      , "longleftrightarrow"
                      , "Longleftarrow"
                      , "Longrightarrow"
                      , "Longleftrightarrow"
                      , "longmapsto"
                      , "sum"
                      , "prod"
                      , "bigcap"
                      , "bigcup"
                      , "bigwedge"
                      , "bigvee"
                      , "bigsqcap"
                      , "bigsqcup"
                      , "coprod"
                      , "bigoplus"
                      , "bigotimes"
                      , "bigodot"
                      , "biguplus"
                      , "int"
                      , "iint"
                      , "iiint"
                      , "oint"
                      , "prime"
                      , "dots"
                      , "ldots"
                      , "cdots"
                      , "vdots"
                      , "ddots"
                      , "forall"
                      , "exists"
                      , "Re"
                      , "Im"
                      , "aleph"
                      , "hbar"
                      , "ell"
                      , "wp"
                      , "emptyset"
                      , "infty"
                      , "partial"
                      , "nabla"
                      , "triangle"
                      , "therefore"
                      , "angle"
                      , "diamond"
                      , "Diamond"
                      , "lozenge"
                      , "neg"
                      , "lnot"
                      , "bot"
                      , "top"
                      , "square"
                      , "Box"
                      , "wr"
                      , "!"
                      , ","
                      , ">"
                      , ":"
                      , ";"
                      , "quad"
                      , "qquad"
                      , "arccos"
                      , "arcsin"
                      , "arctan"
                      , "arg"
                      , "cos"
                      , "cosh"
                      , "cot"
                      , "coth"
                      , "csc"
                      , "deg"
                      , "det"
                      , "dim"
                      , "exp"
                      , "gcd"
                      , "hom"
                      , "inf"
                      , "ker"
                      , "lg"
                      , "lim"
                      , "liminf"
                      , "limsup"
                      , "ln"
                      , "log"
                      , "max"
                      , "min"
                      , "Pr"
                      , "sec"
                      , "sin"
                      , "sinh"
                      , "sup"
                      , "tan"
                      , "tanh" ]
  mapM_ latexCommand2 [ "frac"
                      , "tfrac"
                      , "dfrac"
                      , "stackrel"
                      , "overset"
                      , "underset"
                      , "binom"]

latexCommand0 :: String -> HeX ()
latexCommand0 s = register s $ ctl s

latexCommand1 :: String -> HeX ()
latexCommand1 s = register s $ \d -> ctl s +++ d

latexCommand2 :: String -> HeX ()
latexCommand2 s = register s $ \d1 d2 -> ctl s +++ d1 +++ d2

root :: Maybe Doc -> Doc -> Doc
root x y = "\\sqrt" +++ x' +++ y
  where x' = case x of
                  Just z  -> "[" +++ z +++ "]"
                  Nothing -> mempty

writer :: MathWriter
writer = MathWriter{
   mathFormat = "latex"
 , displayMath = \d ->
     "$$" +++ d +++ "$$"
 , inlineMath = \d ->
     "$" +++ d +++ "$"
 , grouped = \d -> "{" +++ d +++ "}"
 , variable = rawc
 , number = raws
 , operator = raws
 }
